// next-app/src/app/dynamic/page.tsx
import Head from "next/head";
import DynamicHomepage from "../../components/DynamicHomepage/DynamicHomepage";
import DynamicLayout from "../../layouts/DynamicLayout/DynamicLayout";

export default function Home() {
  return (
    <DynamicLayout>
      <DynamicHomepage />
    </DynamicLayout>
  );
}

// solid-app/src/pages/Dynamic.tsx
import { Component } from "solid-js";

import DynamicLayout from "../layouts/DynamicLayout";
import DynamicHomepage from "../components/DynamicHomepage";

const dynamic: Component = () => {
  return (
    <DynamicLayout>
      <DynamicHomepage />
    </DynamicLayout>
  );
};

export default dynamic;
