// qwik-app/src/Layouts/DynamicLayout.tsx
import { Slot, component$ } from "@builder.io/qwik";

import DynamicFooter from "../components/DynamicFooter";
import DynamicHeader from "../components/DynamicHeader";

export default component$(() => {
  return (
    <div class="dialog-off-canvas-main-canvas" data-off-canvas-main-canvas="">
      <DynamicHeader />
      <div
        role="main"
        class="main-container container-fluid js-quickedit-main-content"
      >
        <div class="row">
          <Slot />
        </div>
      </div>
      <DynamicFooter />
    </div>
  );
});

// sveltekit-app/src/layouts/DynamicLayout.svelte
<script>
	import DynamicHeader from '../components/DynamicHeader.svelte';
	import DynamicFooter from '../components/DynamicFooter.svelte';
</script>

<div class="dialog-off-canvas-main-canvas" data-off-canvas-main-canvas="">
	<DynamicHeader />
	<div role="main" class="main-container container-fluid js-quickedit-main-content">
		<div class="row"><slot /></div>
	</div>
	<DynamicFooter />
</div>
