// solid-app/src/App.tsx
import { lazy, type Component } from 'solid-js';
import { Route, Router, Routes } from "@solidjs/router";

// import Index from './pages/Index';
// import Layout from './pages/Layout';
// import Dynamic from './pages/Dynamic';
// import Async from './pages/Async';

const Index = lazy(() => import("./pages/Index"));
const Layout = lazy(() => import("./pages/Layout"));
const Dynamic = lazy(() => import("./pages/Dynamic"));
const Async = lazy(() => import("./pages/Async"));
const Busy = lazy(() => import("./pages/Busy"));
const Counter = lazy(() => import("./pages/Counter"));

const App: Component = () => {
  return (
    <Router>
      <Routes>
        <Route path="/" component={Index} />
        <Route path="/layout" component={Layout} />
        <Route path="/dynamic" component={Dynamic} />
        <Route path="/async" component={Async} />
        <Route path="/busy" component={Busy} />
        <Route path="/counter" component={Counter} />
      </Routes>
    </Router>
  );
};

export default App;

// react-app/src/App.tsx
import { BrowserRouter, Route, Routes } from "react-router-dom";

// import Index from "./pages/Index";
// import Layout from "./pages/Layout";
// import Dynamic from "./layouts/Dynamic";
// import Async from "./layouts/Async";
// import Counter from "./layouts/Counter";

import { lazy } from "react";
const Index = lazy(() => import("./pages/Index"));
const Layout = lazy(() => import("./pages/Layout"));
const Dynamic = lazy(() => import("./pages/Dynamic"));
const Async = lazy(() => import("./pages/Async"));
const Busy = lazy(() => import("./pages/Busy"));
const Counter = lazy(() => import("./pages/Counter"));
const BetterCounter = lazy(() => import("./pages/BetterCounter"));

function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/" element={<Index />} />
        <Route path="/layout" element={<Layout />} />
        <Route path="/dynamic" element={<Dynamic />} />
        <Route path="/async" element={<Async />} />
        <Route path="/busy" element={<Busy />} />
        <Route path="/counter" element={<Counter />} />
        <Route path="/better-counter" element={<BetterCounter />} />
      </Routes>
    </BrowserRouter>
  );
}

export default App;
