// gatsby-app/src/components/Layout/Layout.tsx
import React from "react"

import Footer from "../Footer/Footer";
import Header from "../Header/Header";

// import "./Layout.css"

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div
      className="dialog-off-canvas-main-canvas"
      data-off-canvas-main-canvas=""
    >
      <Header />
      <div
        role="main"
        className="main-container container-fluid js-quickedit-main-content"
      >
        <div className="row">{children}</div>
      </div>
      <Footer />
    </div>
  );
}

// qwik-app/src/routes/layout.tsx
import { component$, Slot } from "@builder.io/qwik";

import Header from "~/components/Header/Header";
import Footer from "~/components/Footer/Footer";

export default component$(() => {
  return (
    <div class="dialog-off-canvas-main-canvas" data-off-canvas-main-canvas="">
      <Header />
      <div
        role="main"
        class="main-container container-fluid js-quickedit-main-content"
      >
        <div class="row">
          <Slot />
        </div>
      </div>
      <Footer />
    </div>
  );
});
