// solid-app/src/layouts/StaticLayout.tsx
import { ParentComponent } from "solid-js";

import Header from "../components/Header";
import Footer from "../components/Footer";

const StaticLayout: ParentComponent = (props) => {
  return (
    <div class="dialog-off-canvas-main-canvas" data-off-canvas-main-canvas="">
      <Header />
      <div
        role="main"
        class="main-container container-fluid js-quickedit-main-content"
      >
        <div class="row">
          {props.children}
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default StaticLayout;

// gatsby-app/src/layouts/StaticLayout.tsx
import type { ReactNode } from "react";

import React from "react";

import Footer from "../components/Footer";
import Header from "../components/Header";

interface IStaticLayoutProps {
  children: ReactNode;
}

function StaticLayout(props: IStaticLayoutProps) {
  const { children } = props;
  return (
    <div
      className="dialog-off-canvas-main-canvas"
      data-off-canvas-main-canvas=""
    >
      <Header />
      <div
        role="main"
        className="main-container container-fluid js-quickedit-main-content"
      >
        <div className="row">{children}</div>
      </div>
      <Footer />
    </div>
  );
}

export default StaticLayout;
