// qwik-app/src/components/AsyncHomepage.tsx
import { component$ } from "@builder.io/qwik";

import AsyncCards, { ICard } from "./AsyncCards";
import AsyncMap from "./AsyncMap";
import AsyncOpenSource, { IOpenSource } from "./AsyncOpenSource";
import AsyncTabs, { ISolution } from "./AsyncTabs";

export interface IProps {
  cards: ICard[];
  openSources: IOpenSource[];
  solutions: ISolution[];
  technologies: ISolution[];
}

export default component$<IProps>((props) => {
  const { cards, openSources, solutions, technologies } = props;
  return (
    <section class="col-sm-12">
      <a id="main-content"></a>
      <div class="region region-content-top">
        <div data-drupal-messages-fallback="" class="hidden"></div>
      </div>

      <div class="region region-content">
        <article
          data-history-node-id="4"
          role="article"
          about="/fr/homepage"
          typeof="schema:WebPage"
          class="page full clearfix"
        >
          <div class="content">
            <div class="field--item">
              <div class="full-new-homepage">
                <div class="block-header-block homepage-yellow">
                  <div class="logo-block-hp">
                    <a href="#">
                      <img
                        class="block-content-block_header_block__btn-logo-smile"
                        src="https://www.smile.eu/themes/custom/smileeu/assets/images/icons/logo_yellow.png"
                      />
                    </a>
                  </div>
                  <div class="container">
                    <div class="field field--name-field-header-text-paragraph field--type-entity-reference-revisions field--label-hidden field--item">
                      <div class="block-content-block_header_block__paragraph new-header-homepage">
                        <div class="text-new-header">
                          <p>CRÉATEUR D&apos;EXPÉRIENCE DIGITALE OUVERTE</p>
                        </div>
                        <div class="link-single-part">
                          <div class="link-content">
                            <a href="/fr/nos-references" class="btn blue">
                              Découvrez nos projets
                            </a>
                          </div>
                        </div>
                        <h1 class="tag-new-header"> #MadeWithSmile</h1>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <AsyncOpenSource openSources={openSources} />
            <AsyncCards cards={cards} />
            <div class="field--item">
              <div class="block-content block-content-map">
                <div class="map--kpi">
                  <div class="field field--name-field-map-kpi field--type-entity-reference field--label-hidden field--items">
                    <div class="field--item">
                      <div class="block-content block-content-kpi singleblock-text">
                        <div class="title"> 17</div>
                        <div class="subtitle"> Agences</div>
                      </div>
                    </div>
                    <div class="field--item">
                      <div class="block-content block-content-kpi singleblock-text">
                        <div class="title"> 9</div>
                        <div class="subtitle"> PAYS</div>
                      </div>
                    </div>
                    <div class="field--item">
                      <div class="block-content block-content-kpi singleblock-text">
                        <div class="title"> 2000</div>
                        <div class="subtitle"> SMILIENS</div>
                      </div>
                    </div>
                  </div>
                  <div class="link-map">
                    <div class="link-map-content">
                      <a href="/fr/groupe/implantations">Découvrez smile</a>
                    </div>
                  </div>
                </div>
                <AsyncMap />
              </div>
            </div>
            <AsyncTabs solutions={solutions} technologies={technologies} />
          </div>
        </article>
      </div>
    </section>
  );
});

// gatsby-app/src/components/AsyncHomepage.tsx
import React from "react";

import AsyncCards, { ICard } from "../components/AsyncCards";
import AsyncMap from "../components/AsyncMap";
import AsyncOpenSource, { IOpenSource } from "../components/AsyncOpenSource";
import AsyncTabs, { ISolution } from "../components/AsyncTabs";

export interface IData {
  cards: ICard[];
  openSources: IOpenSource[];
  solutions: ISolution[];
  technologies: ISolution[];
}

export default function AsyncHomepage({ data }: { data: IData }) {
  const { cards, openSources, solutions, technologies } = data;
  return (
    <section className="col-sm-12">
      <a id="main-content"></a>
      <div className="region region-content-top">
        <div data-drupal-messages-fallback="" className="hidden"></div>
      </div>

      <div className="region region-content">
        <article
          data-history-node-id="4"
          role="article"
          about="/fr/homepage"
          typeof="schema:WebPage"
          className="page full clearfix"
        >
          <div className="content">
            <div className="field--item">
              <div className="full-new-homepage">
                <div className="block-header-block homepage-yellow">
                  <div className="logo-block-hp">
                    <a href="#">
                      <img
                        className="block-content-block_header_block__btn-logo-smile"
                        src="https://www.smile.eu/themes/custom/smileeu/assets/images/icons/logo_yellow.png"
                      />
                    </a>
                  </div>
                  <div className="container">
                    <div className="field field--name-field-header-text-paragraph field--type-entity-reference-revisions field--label-hidden field--item">
                      <div className="block-content-block_header_block__paragraph new-header-homepage">
                        <div className="text-new-header">
                          <p>CRÉATEUR D&apos;EXPÉRIENCE DIGITALE OUVERTE</p>
                        </div>
                        <div className="link-single-part">
                          <div className="link-content">
                            <a href="/fr/nos-references" className="btn blue">
                              Découvrez nos projets
                            </a>
                          </div>
                        </div>
                        <h1 className="tag-new-header"> #MadeWithSmile</h1>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <AsyncOpenSource openSources={openSources} />
            <AsyncCards cards={cards} />
            <div className="field--item">
              <div className="block-content block-content-map">
                <div className="map--kpi">
                  <div className="field field--name-field-map-kpi field--type-entity-reference field--label-hidden field--items">
                    <div className="field--item">
                      <div className="block-content block-content-kpi singleblock-text">
                        <div className="title"> 17</div>
                        <div className="subtitle"> Agences</div>
                      </div>
                    </div>
                    <div className="field--item">
                      <div className="block-content block-content-kpi singleblock-text">
                        <div className="title"> 9</div>
                        <div className="subtitle"> PAYS</div>
                      </div>
                    </div>
                    <div className="field--item">
                      <div className="block-content block-content-kpi singleblock-text">
                        <div className="title"> 2000</div>
                        <div className="subtitle"> SMILIENS</div>
                      </div>
                    </div>
                  </div>
                  <div className="link-map">
                    <div className="link-map-content">
                      <a href="/fr/groupe/implantations">Découvrez smile</a>
                    </div>
                  </div>
                </div>
                <AsyncMap />
              </div>
            </div>
            <AsyncTabs solutions={solutions} technologies={technologies} />
          </div>
        </article>
      </div>
    </section>
  );
}
