// solid-app/src/components/Search.tsx
import type { Component } from "solid-js";

const Search: Component = () => {
  return (
    <input
      title=""
      data-drupal-selector="edit-search-api-fulltext"
      class="form-search form-control"
      placeholder="Mots-clés, technologies, etc."
      type="search"
      id="edit-search-api-fulltext"
      name="search_api_fulltext"
      size={150}
      maxlength={128}
      data-toggle="tooltip"
      data-original-title=""
    />
  );
};

export default Search;

// gatsby-app/src/components/Search.tsx
import React from "react";

export default function Search() {
  return (
    <input
      title=""
      data-drupal-selector="edit-search-api-fulltext"
      className="form-search form-control"
      placeholder="Mots-clés, technologies, etc."
      type="search"
      id="edit-search-api-fulltext"
      name="search_api_fulltext"
      size={150}
      maxLength={128}
      data-toggle="tooltip"
      data-original-title=""
    />
  );
}
