// qwik-app/src/routes/busy/index.tsx
import { routeLoader$, type DocumentHead } from "@builder.io/qwik-city";
import { component$ } from "@builder.io/qwik";

import DynamicLayout from "~/Layouts/DynamicLayout";
import BusyHomepage from "~/components/BusyHomepage";
import { ISolution } from "~/components/AsyncTabs";
import { IOpenSource } from "~/components/AsyncOpenSource";
import { ICard } from "~/components/AsyncCards";

export const useOpenSources = routeLoader$(async () => {
  const res = await fetch("http://localhost:3333/opensource");
  const data = await res.json();
  return data as [IOpenSource, IOpenSource];
});

export const useCards = routeLoader$(async () => {
  const res = await fetch("http://localhost:3333/cards");
  const data = await res.json();
  return data as ICard[];
});

export const useSolutions = routeLoader$(async () => {
  const res = await fetch("http://localhost:3333/solutions");
  const data = await res.json();
  return data as ISolution[];
});

export const useTechnologies = routeLoader$(async () => {
  const res = await fetch("http://localhost:3333/technologies");
  const data = await res.json();
  return data as ISolution[];
});

export default component$(() => {
  const openSources = useOpenSources();
  const cards = useCards();
  const solutions = useSolutions();
  const technologies = useTechnologies();

  return (
    <DynamicLayout>
      <BusyHomepage
        cards={cards.value}
        openSources={openSources.value}
        solutions={solutions.value}
        technologies={technologies.value}
      />
    </DynamicLayout>
  );
});

export const head: DocumentHead = {
  title: "Welcome to Qwik",
  meta: [
    {
      name: "description",
      content: "Qwik site description",
    },
  ],
};

// remix-app/app/routes/busy.tsx
import type { V2_MetaFunction } from "@remix-run/node";
import { useLoaderData } from "@remix-run/react";

import BusyHomepage, { IData } from "~/components/BusyHomepage";
import DynamicLayout from "~/layouts/DynamicLayout";

export const meta: V2_MetaFunction = () => {
  return [
    { title: "New Remix App" },
    { name: "description", content: "Welcome to Remix!" },
  ];
};

export default function Index() {
  const data = useLoaderData<IData>();

  return (
    <DynamicLayout>
      <BusyHomepage data={data} />
    </DynamicLayout>
  );
}

export const loader = async () => {
  const [cards, openSources, solutions, technologies, diff] = await Promise.all(
    [
      fetch("http://localhost:3333/cards").then((r) => r.json()),
      fetch("http://localhost:3333/opensource").then((r) => r.json()),
      fetch("http://localhost:3333/solutions").then((r) => r.json()),
      fetch("http://localhost:3333/technologies").then((r) => r.json()),
      new Promise((resolve) => {
        let start = performance.now();
        for (let i = 0; i < 100_000; i++) {
          for (let j = 0; j < 100_000; j++) {
            if (i % 2 === 0) {
              start += j;
            } else {
              start -= j;
            }
          }
        }
        resolve(Math.round(performance.now() - start));
      }),
    ]
  );
  const data: IData = {
    cards,
    diff,
    openSources,
    solutions,
    technologies,
  };
  return data;
};
