// qwik-app/src/routes/ssr/index.tsx
import { routeLoader$, type DocumentHead } from "@builder.io/qwik-city";
import { component$ } from "@builder.io/qwik";

import DynamicLayout from "~/Layouts/DynamicLayout";
import AsyncHomepage from "~/components/AsyncHomepage";
import { ISolution } from "~/components/AsyncTabs";
import { IOpenSource } from "~/components/AsyncOpenSource";
import { ICard } from "~/components/AsyncCards";

export const useOpenSources = routeLoader$(async () => {
  const res = await fetch("http://localhost:3333/opensource");
  const data = await res.json();
  return data as [IOpenSource, IOpenSource];
});

export const useCards = routeLoader$(async () => {
  const res = await fetch("http://localhost:3333/last");
  const data = await res.json();
  return data as ICard[];
});

export const useSolutions = routeLoader$(async () => {
  const res = await fetch("http://localhost:3333/solutions");
  const data = await res.json();
  return data as ISolution[];
});

export const useTechnologies = routeLoader$(async () => {
  const res = await fetch("http://localhost:3333/technologies");
  const data = await res.json();
  return data as ISolution[];
});

export default component$(() => {
  const openSources = useOpenSources();
  const cards = useCards();
  const solutions = useSolutions();
  const technologies = useTechnologies();

  return (
    <DynamicLayout>
      <AsyncHomepage
        cards={cards.value}
        openSources={openSources.value}
        solutions={solutions.value}
        technologies={technologies.value}
      />
    </DynamicLayout>
  );
});

export const head: DocumentHead = {
  title: "Welcome to Qwik",
  meta: [
    {
      name: "description",
      content: "Qwik site description",
    },
  ],
};

// remix-app/app/routes/ssr.tsx
import type { V2_MetaFunction } from "@remix-run/node";
import { useLoaderData } from "@remix-run/react";

import AsyncHomepage, { IData } from "~/components/AsyncHomepage";
import DynamicLayout from "~/layouts/DynamicLayout";

export const meta: V2_MetaFunction = () => {
  return [
    { title: "New Remix App" },
    { name: "description", content: "Welcome to Remix!" },
  ];
};

export default function Index() {
  const data = useLoaderData<IData>();

  return (
    <DynamicLayout>
      <AsyncHomepage data={data} />
    </DynamicLayout>
  );
}

export const loader = async () => {
  const [cards, openSources, solutions, technologies] = await Promise.all([
    fetch("http://localhost:3333/last").then((r) => r.json()),
    fetch("http://localhost:3333/opensource").then((r) => r.json()),
    fetch("http://localhost:3333/solutions").then((r) => r.json()),
    fetch("http://localhost:3333/technologies").then((r) => r.json()),
  ]);
  const data: IData = {
    cards,
    openSources,
    solutions,
    technologies,
  };
  return data;
};
