// preact-app/src/app.tsx
import Router from "preact-router";
import AsyncRoute from "preact-async-route";

export function App() {
  return (
    <Router>
      <AsyncRoute
        path="/"
        getComponent={() =>
          import("./pages/Index").then((module) => module.default)
        }
      />
      <AsyncRoute
        path="/layout"
        getComponent={() =>
          import("./pages/Layout").then((module) => module.default)
        }
      />
      <AsyncRoute
        path="/dynamic"
        getComponent={() =>
          import("./pages/Dynamic").then((module) => module.default)
        }
      />
      <AsyncRoute
        path="/async"
        getComponent={() =>
          import("./pages/Async").then((module) => module.default)
        }
      />
      <AsyncRoute
        path="/busy"
        getComponent={() =>
          import("./pages/Busy").then((module) => module.default)
        }
      />
      <AsyncRoute
        path="/counter"
        getComponent={() =>
          import("./pages/Counter").then((module) => module.default)
        }
      />
      <AsyncRoute
        path="/better-counter"
        getComponent={() =>
          import("./pages/BetterCounter").then((module) => module.default)
        }
      />
    </Router>
  );
}

// solid-app/src/App.tsx
import { lazy, type Component } from 'solid-js';
import { Route, Router, Routes } from "@solidjs/router";

// import Index from './pages/Index';
// import Layout from './pages/Layout';
// import Dynamic from './pages/Dynamic';
// import Async from './pages/Async';

const Index = lazy(() => import("./pages/Index"));
const Layout = lazy(() => import("./pages/Layout"));
const Dynamic = lazy(() => import("./pages/Dynamic"));
const Async = lazy(() => import("./pages/Async"));
const Busy = lazy(() => import("./pages/Busy"));
const Counter = lazy(() => import("./pages/Counter"));

const App: Component = () => {
  return (
    <Router>
      <Routes>
        <Route path="/" component={Index} />
        <Route path="/layout" component={Layout} />
        <Route path="/dynamic" component={Dynamic} />
        <Route path="/async" component={Async} />
        <Route path="/busy" component={Busy} />
        <Route path="/counter" component={Counter} />
      </Routes>
    </Router>
  );
};

export default App;
