// sveltekit-app/src/layouts/StaticLayout.svelte
<script>
	import Header from '../components/Header.svelte';
	import Footer from '../components/Footer.svelte';
</script>

<div class="dialog-off-canvas-main-canvas" data-off-canvas-main-canvas="">
	<Header />
	<div role="main" class="main-container container-fluid js-quickedit-main-content">
		<div class="row"><slot /></div>
	</div>
	<Footer />
</div>

// qwik-app/src/Layouts/StaticLayout.tsx
import { Slot, component$ } from "@builder.io/qwik";

import Footer from "../components/Footer";
import Header from "../components/Header";

export default component$(() => {
  return (
    <div class="dialog-off-canvas-main-canvas" data-off-canvas-main-canvas="">
      <Header />
      <div
        role="main"
        class="main-container container-fluid js-quickedit-main-content"
      >
        <div class="row">
          <Slot />
        </div>
      </div>
      <Footer />
    </div>
  );
});
