// react-app/src/components/AsyncHomepage.tsx
import { MouseEvent } from "react";

import AsyncCards from "./AsyncCards";
import AsyncMap from "./AsyncMap";
import AsyncOpenSource from "./AsyncOpenSource";
import AsyncTabs from "./AsyncTabs";

interface IAsyncHomepageProps {
  count?: number;
  onStart?: () => void;
}

export default function AsyncHomepage(props: IAsyncHomepageProps) {
  const { count = 2000, onStart } = props;

  function handleStart(event: MouseEvent) {
    event.preventDefault();
    onStart?.();
  }

  return (
    <section className="col-sm-12">
      <a id="main-content"></a>
      <div className="region region-content-top">
        <div data-drupal-messages-fallback="" className="hidden"></div>
      </div>

      <div className="region region-content">
        <article
          data-history-node-id="4"
          role="article"
          about="/fr/homepage"
          typeof="schema:WebPage"
          className="page full clearfix"
        >
          <div className="content">
            <div className="field--item">
              <div className="full-new-homepage">
                <div className="block-header-block homepage-yellow">
                  <div className="logo-block-hp">
                    <a href="#">
                      <img
                        className="block-content-block_header_block__btn-logo-smile"
                        src="https://www.smile.eu/themes/custom/smileeu/assets/images/icons/logo_yellow.png"
                      />
                    </a>
                  </div>
                  <div className="container">
                    <div className="field field--name-field-header-text-paragraph field--type-entity-reference-revisions field--label-hidden field--item">
                      <div className="block-content-block_header_block__paragraph new-header-homepage">
                        <div className="text-new-header">
                          <p>CRÉATEUR D&apos;EXPÉRIENCE DIGITALE OUVERTE</p>
                        </div>
                        <div className="link-single-part">
                          <div className="link-content">
                            <a href="/fr/nos-references" className="btn blue">
                              Découvrez nos projets
                            </a>
                          </div>
                        </div>
                        <h1 className="tag-new-header"> #MadeWithSmile</h1>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <AsyncOpenSource />
            <AsyncCards />
            <div className="field--item">
              <div className="block-content block-content-map">
                <div className="map--kpi">
                  <div className="field field--name-field-map-kpi field--type-entity-reference field--label-hidden field--items">
                    <div className="field--item">
                      <div className="block-content block-content-kpi singleblock-text">
                        <div className="title"> 17</div>
                        <div className="subtitle"> Agences</div>
                      </div>
                    </div>
                    <div className="field--item">
                      <div className="block-content block-content-kpi singleblock-text">
                        <div className="title"> 9</div>
                        <div className="subtitle"> PAYS</div>
                      </div>
                    </div>
                    <div className="field--item">
                      <div className="block-content block-content-kpi singleblock-text">
                        <div className="title"> {count}</div>
                        <div className="subtitle"> SMILIENS</div>
                      </div>
                    </div>
                  </div>
                  <div className="link-map">
                    <div className="link-map-content">
                      <button
                        type="button"
                        onClick={handleStart}
                        style={{ border: 0, background: "transparent" }}
                      >
                        Découvrez smile
                      </button>
                    </div>
                  </div>
                </div>
                <AsyncMap />
              </div>
            </div>
            <AsyncTabs />
          </div>
        </article>
      </div>
    </section>
  );
}

// solid-app/src/components/AsyncHomepage.tsx
import type { Accessor, Component } from "solid-js";

import AsyncTabs from "./AsyncTabs";
import AsyncMap from "./AsyncMap";
import AsyncOpenSources from "./AsyncOpenSources";
import AsyncCards from "./AsyncCards";

interface IAsyncHomepageProps {
  count?: Accessor<number>;
  onStart?: () => void;
}

const AsyncHomepage: Component<IAsyncHomepageProps> = (props) => {
  const { count, onStart } = props;

  function handleStart(event: any) {
    event.preventDefault();
    onStart?.();
  }

  return (
    <section class="col-sm-12">
      <a id="main-content" />
      <div class="region region-content-top">
        <div data-drupal-messages-fallback="" class="hidden" />
      </div>

      <div class="region region-content">
        <article
          data-history-node-id="4"
          role="article"
          about="/fr/homepage"
          typeof="schema:WebPage"
          class="page full clearfix"
        >
          <div class="content">
            <div class="field--item">
              <div class="full-new-homepage">
                <div class="block-header-block homepage-yellow">
                  <div class="logo-block-hp">
                    <a href="#" rel="external">
                      <img
                        class="block-content-block_header_block__btn-logo-smile"
                        src="https://www.smile.eu/themes/custom/smileeu/assets/images/icons/logo_yellow.png"
                      />
                    </a>
                  </div>
                  <div class="container">
                    <div class="field field--name-field-header-text-paragraph field--type-entity-reference-revisions field--label-hidden field--item">
                      <div class="block-content-block_header_block__paragraph new-header-homepage">
                        <div class="text-new-header">
                          <p>CRÉATEUR D&apos;EXPÉRIENCE DIGITALE OUVERTE</p>
                        </div>
                        <div class="link-single-part">
                          <div class="link-content">
                            <a
                              href="/fr/nos-references"
                              class="btn blue"
                              rel="external"
                            >
                              Découvrez nos projets
                            </a>
                          </div>
                        </div>
                        <h1 class="tag-new-header">#MadeWithSmile</h1>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <AsyncOpenSources />
            <AsyncCards />
            <div class="field--item">
              <div class="block-content block-content-map">
                <div class="map--kpi">
                  <div class="field field--name-field-map-kpi field--type-entity-reference field--label-hidden field--items">
                    <div class="field--item">
                      <div class="block-content block-content-kpi singleblock-text">
                        <div class="title">17</div>
                        <div class="subtitle">Agences</div>
                      </div>
                    </div>
                    <div class="field--item">
                      <div class="block-content block-content-kpi singleblock-text">
                        <div class="title">9</div>
                        <div class="subtitle">PAYS</div>
                      </div>
                    </div>
                    <div class="field--item">
                      <div class="block-content block-content-kpi singleblock-text">
                        <div class="title">{count?.() ?? 2000}</div>
                        <div class="subtitle">SMILIENS</div>
                      </div>
                    </div>
                  </div>
                  <div class="link-map">
                    <div class="link-map-content">
                      <button
                        type="button"
                        onClick={handleStart}
                        style="border: 0; background: transparent;"
                      >
                        Découvrez smile
                      </button>
                    </div>
                  </div>
                </div>
                <AsyncMap />
              </div>
            </div>
            <AsyncTabs />
          </div>
        </article>
      </div>
    </section>
  );
};

export default AsyncHomepage;
