// remix-app/app/routes/dynamic.tsx
import type { V2_MetaFunction } from "@remix-run/node";

import DynamicHomepage from "~/components/DynamicHomepage";
import DynamicLayout from "~/layouts/DynamicLayout";

export const meta: V2_MetaFunction = () => {
  return [
    { title: "New Remix App" },
    { name: "description", content: "Welcome to Remix!" },
  ];
};

export default function Index() {
  return (
    <DynamicLayout>
      <DynamicHomepage />
    </DynamicLayout>
  );
}

// qwik-app/src/routes/dynamic/index.tsx
import type { DocumentHead } from "@builder.io/qwik-city";
import { component$ } from "@builder.io/qwik";

import DynamicLayout from "~/Layouts/DynamicLayout/DynamicLayout";
import DynamicHomepage from "~/components/DynamicHomepage/DynamicHomepage";

export default component$(() => {
  return (
    <DynamicLayout>
      <DynamicHomepage />
    </DynamicLayout>
  );
});

export const head: DocumentHead = {
  title: "Welcome to Qwik",
  meta: [
    {
      name: "description",
      content: "Qwik site description",
    },
  ],
};
