// vue-app/src/views/Counter.vue
<script lang="ts" setup>
import { onMounted, ref } from 'vue'

import AsyncHomepage from '../components/AsyncHomepage.vue'
import DynamicLayout from '../layouts/DynamicLayout.vue'

const count = ref(0)
let start = false
let time = 0

const channel = new MessageChannel()
const port = channel.port2

onMounted(() => {
  channel.port1.onmessage = () => {
    count.value = count.value + 1
    increment()
  }
})

function startCount() {
  if (count.value === 0) {
    time = Date.now()
    start = true
    increment()
  } else {
    count.value = 0
  }
}

function increment() {
  if (start) {
    if (Date.now() - time < 1000) {
      port.postMessage('')
    } else {
      start = false
    }
  }
}
</script>
<template>
  <DynamicLayout>
    <AsyncHomepage :count="count" @start="startCount" />
  </DynamicLayout>
</template>

// sveltekit-app/src/routes/counter/+page.svelte
<script lang="ts">
	import type { PageData } from './$types';

	import DynamicLayout from '../../layouts/DynamicLayout.svelte';
	import AsyncHomepage from '../../components/AsyncHomepage.svelte';

	export let data: PageData;

	let count = 0;
	let start = false;
	let time = 0;

	const channel = new MessageChannel();
	const port = channel.port2;
	channel.port1.onmessage = () => {
		count = count + 1;
		increment();
	};

	function startCount() {
		if (count === 0) {
			time = Date.now();
			start = true;
			increment();
		} else {
			count = 0;
		}
	}

	function increment() {
		if (start) {
			if (Date.now() - time < 1000) {
				port.postMessage('');
			} else {
				start = false;
			}
		}
	}
</script>

<DynamicLayout>
	<AsyncHomepage
		cards={data.cards}
		openSources={data.openSources}
		solutions={data.solutions}
		technologies={data.technologies}
		{count}
		on:start={startCount}
	/>
</DynamicLayout>
