// vue-app/src/views/Counter.vue
<script lang="ts" setup>
import { onMounted, ref } from 'vue'

import AsyncHomepage from '../components/AsyncHomepage.vue'
import DynamicLayout from '../layouts/DynamicLayout.vue'

const count = ref(0)
let start = false
let time = 0

const channel = new MessageChannel()
const port = channel.port2

onMounted(() => {
  channel.port1.onmessage = () => {
    count.value = count.value + 1
    increment()
  }
})

function startCount() {
  if (count.value === 0) {
    time = Date.now()
    start = true
    increment()
  } else {
    count.value = 0
  }
}

function increment() {
  if (start) {
    if (Date.now() - time < 1000) {
      port.postMessage('')
    } else {
      start = false
    }
  }
}
</script>
<template>
  <DynamicLayout>
    <AsyncHomepage :count="count" @start="startCount" />
  </DynamicLayout>
</template>

// react-app/src/pages/Counter.tsx
import { useEffect, useRef, useState } from "react";

import AsyncHomepage from "../components/AsyncHomepage";
import DynamicLayout from "../layouts/DynamicLayout";

const channel = new MessageChannel();
const port = channel.port2;

export default function Counter() {
  const [count, setCount] = useState(0);
  const start = useRef(false);
  const time = useRef(0);

  useEffect(() => {
    channel.port1.onmessage = () => {
      setCount((x) => x + 1);
      increment();
    };
  }, []);

  function startCount() {
    if (count === 0) {
      time.current = Date.now();
      start.current = true;
      increment();
    } else {
      setCount(0);
    }
  }

  function increment() {
    if (start) {
      if (Date.now() - time.current < 1000) {
        port.postMessage("");
      } else {
        start.current = false;
      }
    }
  }

  return (
    <DynamicLayout>
      <AsyncHomepage count={count} onStart={startCount} />
    </DynamicLayout>
  );
}
